# Default values for wine_mt5.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: matsu2254/wine64-x11-novnc-docker
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

wine:
  data:
    size: 10Gi
    storageClass: hostpath

config:
  # TIMEFRAME_M1   1
  # TIMEFRAME_M2   2
  # TIMEFRAME_M3   3
  # TIMEFRAME_M4   4
  # TIMEFRAME_M5   5
  # TIMEFRAME_M6   6
  # TIMEFRAME_M10   10
  # TIMEFRAME_M12   12
  # TIMEFRAME_M15   15
  # TIMEFRAME_M20   20
  # TIMEFRAME_M30   30
  # TIMEFRAME_H1   16385
  # TIMEFRAME_H2   16386
  # TIMEFRAME_H4   16388
  # TIMEFRAME_H3   16387
  # TIMEFRAME_H6   16390
  # TIMEFRAME_H8   16392
  # TIMEFRAME_H12   16396
  # TIMEFRAME_D1   16408
  # TIMEFRAME_W1   32769
  # TIMEFRAME_MN1   49153
  apiVersion: v0.1
  kind: mt5_uploader_config
  metadata:
    name: config_for...
  data:
    CONFIG:
      INFLUXDB_BUCKET: test
      INFLUXDB_ORG: influxdata
      INFLUXDB_TOKEN: 78mdMPrH02UaKsrsb6Q2Ofj0neRVfRNDaFfrN2RWqreobbh3RtP7jyKX9-Ktvt-JBAthd1FPnZggkRANHi9T8w==
      INFLUXDB_URL: http://192.168.0.15
    GETDATA:
    - REPEAT: 20
      SYMBOL: USDJPY
      TAG: Timeframe
      TIMEFRAME: TIMEFRAME_H4
      GOBACK: days=60
    - REPEAT: 20
      SYMBOL: AUDJPY
      TAG: Timeframe
      TIMEFRAME: Tick
      GOBACK: days=3

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 8080
  nodePort: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


nodeSelector: {}

tolerations: []

affinity: {}
