apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wine_mt5.fullname" . }}
  labels:
    {{- include "wine_mt5.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "wine_mt5.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wine_mt5.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: vnc
              containerPort: {{ .Values.service.port }}
              protocol: TCP

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
            - name: winepre
              mountPath: /winepre
            - name: supervisor-setting
              mountPath: /etc/supervisor/conf.d
            - name: code
              mountPath: /CODE
      
      volumes:
        - name: supervisor-setting
          configMap:
            name: {{ .Chart.Name }}-supervisor-setting
        - name: code
          configMap:
            name: {{ .Chart.Name }}-code-configmap
        - name: winepre
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-winepre
            
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
