apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ .Chart.Name }}-winepre'
spec:
  resources:
    requests:
      storage: {{ .Values.wine.data.size }}
  volumeMode: Filesystem
  storageClassName: {{ .Values.wine.data.storageClass }}
  accessModes:
    - ReadWriteOnce
