apiVersion: v1
kind: PersistentVolume
metadata:
  name: wine-mt5-pv
spec:
  capacity:
    storage: 11Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: hostpath
  hostPath:
    path: /smb/winedata/winepre2
